name: clima
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  geolocator: ^5.3.0
  http: ^0.12.0+4
  flutter_spinkit: ^4.1.2
  weather_icons: 2.0.1
  intl: ^0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - images/

  fonts:
  - family: Baloo
    fonts:
    - asset: fonts/Baloo2-Regular.ttf
  - family: BalooBold
    fonts:
    - asset: fonts/Baloo2-ExtraBold.ttf
  - family: Quicksand
    fonts:
    - asset: fonts/Quicksand-VariableFont_wght.ttf
